# Generated by Django 3.0.7 on 2020-06-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowme', '0002_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='owner',
            new_name='user',
        ),
    ]
