# Generated by Django 3.0.7 on 2020-06-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowme', '0003_auto_20200619_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
