# Generated by Django 3.0.7 on 2020-12-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20201227_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(),
        ),
    ]
